# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty
language: python

env:
  - DOCKER_COMPOSE_VERSION=1.23.2
  - CODECOV_TOKEN="7b03bdb0-6425-4a52-b78a-b8cfb92206b5"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  -
cache:
  - conda
  - pip

services:
  - docker

script:
  - make test

after_success:
  - coveralls
