version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - ./pyamber:/amberdata/pyamber:ro
      - ./test:/amberdata/test:ro
      - ./artifacts:/amberdata/artifacts
