version: '3.6'
services:
  web:
     build:
       context: .
       dockerfile: Dockerfile
       target: production
     volumes:
       # sharing volumes like this is won't respect the .dockerignore file!
       - ./pyamber:/amberdata/pyamber:ro
       - ./config:/amberdata/config:ro
